name: gcampus
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - pip=25
  - libgdal>=3.10,<4.0a0
  - glib>=2.82,<3.0a0
  - pango>=1.56,<2.0a0
  - pip:
      - '-r requirements-dev.txt'
