# Generated by Django 4.0.3 on 2022-03-29 09:55
from django.conf import settings
from django.db import migrations


TSVECTOR_CONF = getattr(settings, "TSVECTOR_CONF", "german")


class Migration(migrations.Migration):
    dependencies = [
        ("gcampuscore", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(
            f"""
            ALTER TABLE "gcampuscore_measurement"
                DROP COLUMN "search_vector" CASCADE,
                ADD COLUMN "search_vector" tsvector GENERATED ALWAYS AS (
                    setweight(to_tsvector('{TSVECTOR_CONF}', coalesce("name", '')), 'A') ||
                    setweight(to_tsvector('{TSVECTOR_CONF}', coalesce("comment",'')), 'B') ||
                    setweight(to_tsvector('{TSVECTOR_CONF}', coalesce("location_name",'')), 'A')
                ) STORED
        """,
            reverse_sql="",
        ),  # noqa
    ]
