# Generated by Django 3.1.7 on 2021-03-10 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gcampuscore", "0002_auto_20210309_2242"),
    ]

    operations = [
        migrations.AddField(
            model_name="measurement",
            name="location_name",
            field=models.CharField(blank=True, max_length=280),
        ),
    ]
