# Generated by Django 4.0.4 on 2022-05-06 13:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gcampuscore", "0004_location_help_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="measurement",
            name="document",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="documents/measurement",
                verbose_name="Document",
            ),
        ),
    ]
