# Generated by Django 3.1.7 on 2021-04-07 16:04

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("gcampuscore", "0004_auto_20210310_1205"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="datapoint",
            options={
                "verbose_name": "Data point",
                "verbose_name_plural": "Data points",
            },
        ),
        migrations.AlterModelOptions(
            name="datatype",
            options={"verbose_name": "Data type", "verbose_name_plural": "Data types"},
        ),
        migrations.AlterModelOptions(
            name="measurement",
            options={
                "verbose_name": "Measurement",
                "verbose_name_plural": "Measurements",
            },
        ),
        # migrations.AddField(
        #     model_name="datatype",
        #     name="unit",
        #     field=models.CharField(blank=True, max_length=10, verbose_name="Unit"),
        # ),
        migrations.AlterField(
            model_name="datapoint",
            name="comment",
            field=models.TextField(blank=True, verbose_name="Comment"),
        ),
        migrations.AlterField(
            model_name="datapoint",
            name="data_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="gcampuscore.datatype",
                verbose_name="Data type",
            ),
        ),
        migrations.AlterField(
            model_name="datapoint",
            name="measurement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="data_points",
                to="gcampuscore.measurement",
                verbose_name="Associated measurement",
            ),
        ),
        migrations.AlterField(
            model_name="datapoint",
            name="value",
            field=models.FloatField(verbose_name="Value"),
        ),
        migrations.AlterField(
            model_name="datatype",
            name="name",
            field=models.CharField(blank=True, max_length=280, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="measurement",
            name="comment",
            field=models.TextField(blank=True, verbose_name="Comment"),
        ),
        migrations.AlterField(
            model_name="measurement",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                srid=4326, verbose_name="Location"
            ),
        ),
        migrations.AlterField(
            model_name="measurement",
            name="location_name",
            field=models.CharField(
                blank=True,
                help_text="An approximated location for the measurement",
                max_length=280,
                null=True,
                verbose_name="Location name",
            ),
        ),
        migrations.AlterField(
            model_name="measurement",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="Your name or team name",
                max_length=280,
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="measurement",
            name="time",
            field=models.DateTimeField(
                help_text="Date and time of the measurement",
                verbose_name="Measurement Time",
            ),
        ),
    ]
