# Generated by Django 3.1.7 on 2021-04-05 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gcampuscore", "0005_auto_20210312_1438"),
    ]

    operations = [
        migrations.AlterField(
            model_name="measurement",
            name="time",
            field=models.DateTimeField(
                help_text="Date and time of the measurement",
                verbose_name="Measurement Time",
            ),
        ),
    ]
