# Generated by Django 3.1.7 on 2021-04-07 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gcampuscore", "0007_datatype_unit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datatype",
            name="unit",
            field=models.CharField(default="mg/l", max_length=10, verbose_name="Unit"),
        ),
    ]
