# Generated by Django 4.1 on 2022-11-02 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "gcampuscore",
            "0009_bachindex_saprobicindex_structureindex_trophicindex_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="bachindex",
            name="description",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="measurement",
            name="internal_comment",
            field=models.TextField(
                blank=True, null=True, verbose_name="internal comment"
            ),
        ),
        migrations.AlterField(
            model_name="measurement",
            name="requires_review",
            field=models.BooleanField(default=False, verbose_name="requires review"),
        ),
        migrations.AlterField(
            model_name="parametertype",
            name="category",
            field=models.CharField(
                choices=[
                    (None, "unknown"),
                    ("undefined", "undefined"),
                    ("biological", "biological"),
                    ("chemical", "chemical"),
                    ("physical", "physical"),
                ],
                default="undefined",
                max_length=20,
                verbose_name="Category",
            ),
        ),
        migrations.AlterField(
            model_name="saprobicindex",
            name="description",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="structureindex",
            name="description",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="trophicindex",
            name="description",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="water",
            name="internal_comment",
            field=models.TextField(
                blank=True, null=True, verbose_name="internal comment"
            ),
        ),
        migrations.AlterField(
            model_name="water",
            name="requires_update",
            field=models.BooleanField(default=False, verbose_name="requires update"),
        ),
    ]
