# Generated by Django 3.1.7 on 2021-04-12 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gcampuscore", "0009_auto_20210407_1316"),
        ("gcampuscore", "0005_auto_20210407_1804"),
    ]

    operations = []
