# Generated by Django 4.1 on 2022-11-03 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gcampuscore", "0009_water_search"),
    ]

    operations = [
        migrations.CreateModel(
            name="BACHIndex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.IntegerField(
                        blank=True, default=0, null=True, verbose_name="Value"
                    ),
                ),
                (
                    "classification",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="Classification",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Description"
                    ),
                ),
                (
                    "validity",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=3,
                        verbose_name="Validity",
                    ),
                ),
                (
                    "measurement",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bach_index",
                        to="gcampuscore.measurement",
                    ),
                ),
            ],
            options={
                "verbose_name": "BACH Index",
                "verbose_name_plural": "BACH Indices",
            },
        ),
        migrations.CreateModel(
            name="SaprobicIndex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.IntegerField(
                        blank=True, default=0, null=True, verbose_name="Value"
                    ),
                ),
                (
                    "classification",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="Classification",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Description"
                    ),
                ),
                (
                    "validity",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=3,
                        verbose_name="Validity",
                    ),
                ),
                (
                    "measurement",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saprobic_index",
                        to="gcampuscore.measurement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Saprobic Index",
                "verbose_name_plural": "Saprobic Indices",
            },
        ),
        migrations.CreateModel(
            name="StructureIndex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.IntegerField(
                        blank=True, default=0, null=True, verbose_name="Value"
                    ),
                ),
                (
                    "classification",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="Classification",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Description"
                    ),
                ),
                (
                    "validity",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=3,
                        verbose_name="Validity",
                    ),
                ),
                (
                    "utilization",
                    models.CharField(
                        choices=[
                            ("natural", "natural forest (deciduous trees)"),
                            (
                                "extensive",
                                "extensive use: unfertilized or small grazed meadows, no buildings",
                            ),
                            (
                                "mixed",
                                "smaller fields, pastures or gardens, coniferous forest",
                            ),
                            (
                                "intensive",
                                "intensive farming and arable land, some buildings",
                            ),
                            ("artificial", "village, industrial area"),
                            ("unknown", "unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                        verbose_name="Environment utilization",
                    ),
                ),
                (
                    "margin",
                    models.CharField(
                        choices=[
                            ("large", "> 20 m"),
                            ("medium", "approx. 5-20 m"),
                            ("small", "approx. 2-5 m"),
                            ("tiny", "< 2 m"),
                            ("none", "non-existent"),
                            ("unknown", "unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                        verbose_name="Margin width",
                    ),
                ),
                (
                    "course",
                    models.CharField(
                        choices=[
                            ("natural", "curved (not modified)"),
                            ("changed", "partly curved (partly modified)"),
                            ("stretched", "stretched (moderately modified)"),
                            ("straight", "straight (strongly modified)"),
                            ("artificial", "straight (completely modified)"),
                            ("unknown", "unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                        verbose_name="Water course",
                    ),
                ),
                (
                    "bank_vegetation",
                    models.CharField(
                        choices=[
                            (
                                "continuous",
                                "continuous grove (deciduous trees), several meters wide",
                            ),
                            (
                                "narrow",
                                "narrow continuous grove, wet meadow, tall herbaceous plants or reeds",
                            ),
                            (
                                "sparse",
                                "sparse grove, herbaceous vegetation of stinging nettles and other nutrient indicators",
                            ),
                            (
                                "non-native",
                                "individual trees, non-native vegetation (cottonwoods, conifers, or ornamental shrubs), mowed bank",
                            ),
                            (
                                "artificial",
                                "no trees, no herbaceous vegetation, paved bank",
                            ),
                            ("unknown", "unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                        verbose_name="Water course",
                    ),
                ),
                (
                    "bank_structure",
                    models.CharField(
                        choices=[
                            (
                                "natural",
                                "no fixed banks, many inlets and widenings, water body can expand unhindered in width",
                            ),
                            (
                                "straight",
                                "banks straightened, not visibly fixed, some indentations and widenings",
                            ),
                            (
                                "strengthened",
                                "banks partly strengthened (< 50%), bank failures possible",
                            ),
                            (
                                "fixed",
                                "banks predominantly strengthened (>50%) by stone fills or wooden piles.",
                            ),
                            (
                                "artificial",
                                "straight bank, steep slope, strengthened (pavement, concrete or similar)",
                            ),
                            ("unknown", "unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                        verbose_name="Water course",
                    ),
                ),
                (
                    "cross_section",
                    models.CharField(
                        choices=[
                            ("very-shallow", "very shallow (width:depth > 10:1)"),
                            ("shallow", "shallow (width:depth approx. 5:1)"),
                            ("moderate", "moderately deep (width:depth approx. 3:1)"),
                            ("deep", "deep (width:depth approx. 2:1)"),
                            ("very-deep", "very deep (width:depth < 2:1)"),
                            ("unknown", "unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                        verbose_name="Water cross-section",
                    ),
                ),
                (
                    "flow",
                    models.CharField(
                        choices=[
                            (
                                "mosaic",
                                "mosaic-like, different flow patterns next to and behind each other",
                            ),
                            (
                                "alternating",
                                "fast and slow flowing water alternate in close succession",
                            ),
                            (
                                "intervals",
                                "alternation of slow and fast flowing water at longer intervals",
                            ),
                            (
                                "mixed",
                                "alternation of slow and fast flowing water recognizable",
                            ),
                            ("uniform", "uniform flowing water"),
                            ("unknown", "unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                        verbose_name="Water flow pattern",
                    ),
                ),
                (
                    "depth_variance",
                    models.CharField(
                        choices=[
                            (
                                "mosaic",
                                "mosaic-like alternation between deep and shallow water areas",
                            ),
                            ("major", "major depth variance"),
                            ("moderate", "moderate depth variance"),
                            ("minor", "minor depth variance"),
                            ("uniform", "no depth variance"),
                            ("unknown", "unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                        verbose_name="Variance of water depth",
                    ),
                ),
                (
                    "riverbed",
                    models.CharField(
                        choices=[
                            (
                                "mosaic",
                                "mosaic-like distribution of sand/gravel/stones and deadwood, pronounced formation of islands",
                            ),
                            (
                                "diverse",
                                "diversified riverbed (sand/gravel/stones/deadwood), rudimentary formation of islands",
                            ),
                            (
                                "intervals",
                                "more uniform riverbed, different structures at greater intervals",
                            ),
                            (
                                "mixed",
                                "silted/paved/concreted riverbed over long stretches",
                            ),
                            (
                                "uniform",
                                "uniform riverbed, completely silted/paved/concreted",
                            ),
                            ("unknown", "unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                        verbose_name="Riverbed",
                    ),
                ),
                (
                    "continuity",
                    models.CharField(
                        choices=[
                            ("natural", "no obstacles, natural waterfall/cascade"),
                            (
                                "step",
                                "piping < 2 m, artificial step of single stones, can be overcome by fish and invertebrates",
                            ),
                            (
                                "obstacle",
                                "piping 2-5m, minor step (< 30 cm), can be overcome by fish, fish ladder",
                            ),
                            (
                                "hindrance",
                                "piping 5-10m, major step or other barriers (30-100 cm)",
                            ),
                            (
                                "blocked",
                                "piping > 10 m, step or other barriers > 100 cm",
                            ),
                            ("unknown", "unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                        verbose_name="Continuity",
                    ),
                ),
                (
                    "measurement",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="structure_index",
                        to="gcampuscore.measurement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Physical-Structural Index",
                "verbose_name_plural": "Physical-Structural Indices",
            },
        ),
        migrations.CreateModel(
            name="TrophicIndex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.IntegerField(
                        blank=True, default=0, null=True, verbose_name="Value"
                    ),
                ),
                (
                    "classification",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="Classification",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Description"
                    ),
                ),
                (
                    "validity",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=3,
                        verbose_name="Validity",
                    ),
                ),
                (
                    "measurement",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trophic_index",
                        to="gcampuscore.measurement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Trophic Index",
                "verbose_name_plural": "Trophic Indices",
            },
        ),
        migrations.AddField(
            model_name="parametertype",
            name="category",
            field=models.CharField(
                choices=[
                    (None, "unknown"),
                    ("undefined", "undefined"),
                    ("biological", "biological"),
                    ("chemical", "chemical"),
                    ("physical", "physical"),
                ],
                default="undefined",
                max_length=20,
                verbose_name="Category",
            ),
        ),
        migrations.AddField(
            model_name="parametertype",
            name="identifier",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Identifier"
            ),
        ),
        migrations.DeleteModel(
            name="Limit",
        ),
    ]
