# Generated by Django 3.1.7 on 2021-04-14 09:50

import django.contrib.gis.db.models.fields
import django.contrib.postgres.search
from django.db import migrations, models

from gcampus.core.models.util import get_search_vector, update_search_vector
from gcampus.core.models import Measurement as MeasurementModel


def index_existing(apps, schema_editor):
    Measurement = apps.get_model("gcampuscore", "Measurement")  # noqa
    vector = get_search_vector(MeasurementModel)
    update_search_vector(Measurement, vector)


class Migration(migrations.Migration):

    dependencies = [
        ('gcampuscore', '0010_merge_20210412_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(editable=False, null=True),
        ),
        migrations.RunPython(index_existing)
    ]
