# Generated by Django 4.1 on 2022-11-03 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "gcampuscore",
            "0010_bachindex_saprobicindex_structureindex_trophicindex_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="bachindex",
            name="value",
            field=models.FloatField(
                blank=True, default=0, null=True, verbose_name="Value"
            ),
        ),
        migrations.AlterField(
            model_name="saprobicindex",
            name="value",
            field=models.FloatField(
                blank=True, default=0, null=True, verbose_name="Value"
            ),
        ),
        migrations.AlterField(
            model_name="structureindex",
            name="value",
            field=models.FloatField(
                blank=True, default=0, null=True, verbose_name="Value"
            ),
        ),
        migrations.AlterField(
            model_name="trophicindex",
            name="value",
            field=models.FloatField(
                blank=True, default=0, null=True, verbose_name="Value"
            ),
        ),
    ]
