#  Copyright (C) 2021 desklab gUG (haftungsbeschränkt)
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
#
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.

# Generated by Django 3.1.7 on 2021-04-19 14:05

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.conf import settings
from django.db import migrations

TSVECTOR_CONF = getattr(settings, "TSVECTOR_CONF", "german")


class Migration(migrations.Migration):

    dependencies = [
        ("gcampuscore", "0010_merge_20210412_1815"),
    ]

    operations = [
        migrations.AddField(
            model_name="measurement",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(
                editable=False, null=True
            ),
        ),
        migrations.AddIndex(
            model_name="measurement",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="gcampuscore_search__13d7ba_gin"
            ),
        ),
        migrations.RunSQL(
            f"""
            ALTER TABLE "gcampuscore_measurement"
                DROP COLUMN "search_vector" CASCADE,
                ADD COLUMN "search_vector" tsvector GENERATED ALWAYS AS (
                    setweight(to_tsvector('{TSVECTOR_CONF}', coalesce("name", '')), 'A') ||
                    setweight(to_tsvector('{TSVECTOR_CONF}', coalesce("comment",'')), 'B') ||
                    setweight(to_tsvector('{TSVECTOR_CONF}', coalesce("location_name",'')), 'A')
                ) STORED
        """,
            reverse_sql="",
        ),  # noqa
    ]
