# Generated by Django 3.1.7 on 2021-04-19 14:05

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations
from django.conf import settings


TSVECTOR_CONF = getattr(settings, "TSVECTOR_CONF", "german")


class Migration(migrations.Migration):

    dependencies = [
        ("gcampuscore", "0010_merge_20210412_1815"),
    ]

    operations = [
        migrations.AddField(
            model_name="measurement",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(
                editable=False, null=True
            ),
        ),
        migrations.AddIndex(
            model_name="measurement",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="gcampuscore_search__13d7ba_gin"
            ),
        ),
        migrations.RunSQL(
            f"""
            ALTER TABLE "gcampuscore_measurement"
                DROP COLUMN "search_vector" CASCADE,
                ADD COLUMN "search_vector" tsvector GENERATED ALWAYS AS (
                    setweight(to_tsvector('{TSVECTOR_CONF}', coalesce("name", '')), 'A') ||
                    setweight(to_tsvector('{TSVECTOR_CONF}', coalesce("comment",'')), 'B') ||
                    setweight(to_tsvector('{TSVECTOR_CONF}', coalesce("location_name",'')), 'A')
                ) STORED
        """,
            reverse_sql="",
        ),  # noqa
    ]
