# Generated by Django 3.1.7 on 2021-05-17 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gcampuscore", "0011_auto_20210419_1605"),
    ]

    operations = [
        migrations.AddField(
            model_name="measurement",
            name="osm_id",
            field=models.BigIntegerField(
                blank=True, default=None, null=True, verbose_name="OpenStreetMap ID"
            ),
        ),
    ]
