# Generated by Django 4.1 on 2022-12-07 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gcampuscore", "0011_measurement_data_quality_warning_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Calibration",
        ),
    ]
