# Generated by Django 4.1 on 2023-01-04 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gcampuscore", "0012_delete_calibration"),
    ]

    operations = [
        migrations.RenameField(
            model_name="measurement",
            old_name="data_quality_warning",
            new_name="parameter_quality_warning",
        ),
    ]
