# Generated by Django 3.1.7 on 2021-05-22 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gcampuscore', '0013_studenttoken_teachertoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='token',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='gcampuscore.studenttoken'),
        ),
    ]
