# Generated by Django 3.1.7 on 2021-05-30 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gcampuscore", "0014_measurement_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studenttoken",
            name="token",
            field=models.CharField(max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name="teachertoken",
            name="token",
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
