# Generated by Django 3.1.7 on 2021-05-31 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gcampuscore", "0015_auto_20210530_1616"),
        ("gcampuscore", "0015_auto_20210530_1846"),
    ]

    operations = []
