#  Copyright (C) 2021 desklab gUG
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
#
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.

# Generated by Django 3.1.7 on 2021-06-11 08:08

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gcampuscore", "0018_auto_20210604_1052"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="datapoint",
            options={
                "default_manager_name": "all_objects",
                "verbose_name": "Data point",
                "verbose_name_plural": "Data points",
            },
        ),
        migrations.AlterModelOptions(
            name="measurement",
            options={
                "default_manager_name": "all_objects",
                "verbose_name": "Measurement",
                "verbose_name_plural": "Measurements",
            },
        ),
        migrations.AlterModelManagers(
            name="datapoint",
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="measurement",
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
