# Generated by Django 3.1.7 on 2021-06-11 07:54

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('gcampuscore', '0018_auto_20210604_1052'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datapoint',
            options={'default_manager_name': 'all_objects', 'verbose_name': 'Data point', 'verbose_name_plural': 'Data points'},
        ),
        migrations.AlterModelOptions(
            name='measurement',
            options={'default_manager_name': 'all_objects', 'verbose_name': 'Measurement', 'verbose_name_plural': 'Measurements'},
        ),
        migrations.AlterModelManagers(
            name='datapoint',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='measurement',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
