# Generated by Django 3.1.7 on 2021-06-14 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gcampusauth', '0001_initial'),
        ('gcampuscore', '0019_auto_20210611_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='token',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='gcampusauth.studenttoken'),
        ),
        migrations.DeleteModel(
            name='StudentToken',
        ),
        migrations.DeleteModel(
            name='TeacherToken',
        ),
    ]
