# Generated by Django 3.1.7 on 2021-06-14 12:24
from django.conf import settings
from django.db import migrations


TSVECTOR_CONF = getattr(settings, "TSVECTOR_CONF", "german")


class Migration(migrations.Migration):

    dependencies = [
        ("gcampuscore", "0020_auto_20210614_1240"),
    ]

    operations = [
        migrations.RunSQL(
            f"""
            ALTER TABLE "gcampuscore_measurement"
                DROP COLUMN "search_vector" CASCADE,
                ADD COLUMN "search_vector" tsvector GENERATED ALWAYS AS (
                    setweight(to_tsvector('{TSVECTOR_CONF}', coalesce("name", '')), 'A') ||
                    setweight(to_tsvector('{TSVECTOR_CONF}', coalesce("comment",'')), 'B') ||
                    setweight(to_tsvector('{TSVECTOR_CONF}', coalesce("location_name",'')), 'A') ||
                    setweight(to_tsvector('{TSVECTOR_CONF}', coalesce("water_name",'')), 'A')
                ) STORED
        """,
            reverse_sql=f""""
            ALTER TABLE "gcampuscore_measurement"
                DROP COLUMN "search_vector" CASCADE,
                ADD COLUMN "search_vector" tsvector GENERATED ALWAYS AS (
                    setweight(to_tsvector('{TSVECTOR_CONF}', coalesce("name", '')), 'A') ||
                    setweight(to_tsvector('{TSVECTOR_CONF}', coalesce("comment",'')), 'B') ||
                    setweight(to_tsvector('{TSVECTOR_CONF}', coalesce("location_name",'')), 'A')
                ) STORED
            """,
        ),  # noqa
    ]
