# Generated by Django 3.1.7 on 2021-10-11 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gcampuscore', '0021_update_search'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DataPoint',
            new_name='Parameter',
        ),
    ]
