# Generated by Django 3.2.8 on 2021-12-14 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gcampuscore", "0028_auto_20211214_1302"),
    ]

    operations = [
        migrations.AddField(
            model_name="limit",
            name="graph_color",
            field=models.CharField(default="red", max_length=20),
        ),
    ]
