# Generated by Django 4.0.2 on 2022-03-02 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "gcampusauth",
            "0012_alter_accesskey_options_alter_coursetoken_options_and_more",
        ),
        (
            "gcampuscore",
            "0030_alter_measurement_comment_alter_measurement_time_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="measurement",
            name="comment",
            field=models.TextField(
                blank=True,
                help_text="Note on your measurement. This will be publicly visible.",
                verbose_name="Note",
            ),
        ),
        migrations.AlterField(
            model_name="measurement",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="Your forename or team name. This will be publicly visible.",
                max_length=280,
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="measurement",
            name="token",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="measurements",
                to="gcampusauth.accesskey",
            ),
        ),
    ]
