# Generated by Django 4.0 on 2022-03-26 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcampuscore', '0030_alter_measurement_comment_alter_measurement_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametertype',
            name='calibration_formula',
            field=models.CharField(blank=True, max_length=100, verbose_name='Formula'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='comment',
            field=models.TextField(blank=True, help_text='Note on your measurement. This will be publicly visible.', verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='name',
            field=models.CharField(blank=True, help_text='Your forename or team name. This will be publicly visible.', max_length=280, verbose_name='Name'),
        ),
    ]
