# Generated by Django 4.0.2 on 2022-03-02 16:39

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "gcampuscore",
            "0031_alter_measurement_comment_alter_measurement_name_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Water",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=280, verbose_name="Name")),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.GeometryCollectionField(
                        srid=4326
                    ),
                ),
                (
                    "osm_id",
                    models.BigIntegerField(
                        unique=True, verbose_name="OpenStreetMap ID"
                    ),
                ),
            ],
            options={
                "verbose_name": "Water",
                "verbose_name_plural": "Waters",
                "ordering": ("name",),
            },
        ),
    ]
