# Generated by Django 4.0.3 on 2022-03-24 20:27

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "gcampuscore",
            "0031_alter_measurement_comment_alter_measurement_name_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Water",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.GeometryField(
                        srid=4326, verbose_name="Geometry"
                    ),
                ),
                (
                    "tags",
                    models.JSONField(blank=True, default=dict, verbose_name="Tags"),
                ),
                (
                    "osm_id",
                    models.BigIntegerField(
                        null=True, unique=True, verbose_name="OpenStreetMap ID"
                    ),
                ),
                (
                    "osm_element_type",
                    models.CharField(
                        choices=[
                            ("node", "node"),
                            ("way", "way"),
                            ("relation", "relation"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "flow_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            (None, "unknown"),
                            ("standing", "standing water"),
                            ("running", "running water"),
                        ],
                        max_length=16,
                        null=True,
                        verbose_name="Flow type",
                    ),
                ),
                (
                    "water_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            (None, "unknown"),
                            ("wetland", "wetland"),
                            ("coastline", "coastline"),
                            ("bay", "bay"),
                            ("river", "river"),
                            ("stream", "stream"),
                            ("tidal_channel", "tidal channel"),
                            ("canal", "canal"),
                            ("drain", "drain"),
                            ("ditch", "ditch"),
                            ("lagoon", "lagoon"),
                            ("oxbow", "oxbow"),
                            ("lake", "lake"),
                            ("basin", "basin"),
                            ("harbour", "harbour"),
                            ("pond", "pond"),
                            ("reservoir", "reservoir"),
                            ("wastewater", "wastewater"),
                            ("spring", "spring"),
                        ],
                        max_length=16,
                        null=True,
                        verbose_name="Water type",
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=200)),
            ],
            options={
                "verbose_name": "Water",
                "verbose_name_plural": "Waters",
                "ordering": ("name", "osm_id"),
            },
        ),
    ]
