# Generated by Django 4.0.3 on 2022-03-25 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gcampuscore', '0032_water'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurement',
            name='osm_id',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='water_name',
        ),
        migrations.AddField(
            model_name='measurement',
            name='water',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='measurements', to='gcampuscore.water'),
            preserve_default=False,
        ),
    ]
