# Generated by Django 4.0.2 on 2022-03-16 15:50

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gcampuscore", "0032_water"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="water",
            options={
                "ordering": ("name", "osm_id"),
                "verbose_name": "Water",
                "verbose_name_plural": "Waters",
            },
        ),
        migrations.AddField(
            model_name="water",
            name="flow_type",
            field=models.CharField(
                blank=True,
                choices=[
                    (None, "unknown"),
                    ("standing", "standing water"),
                    ("running", "running water"),
                ],
                max_length=16,
                verbose_name="Flow type",
            ),
        ),
        migrations.AddField(
            model_name="water",
            name="osm_element_type",
            field=models.CharField(
                choices=[("node", "node"), ("way", "way"), ("relation", "relation")],
                default="relation",
                max_length=16,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="water",
            name="tags",
            field=models.JSONField(blank=True, default=dict, verbose_name="Tags"),
        ),
        migrations.AddField(
            model_name="water",
            name="water_type",
            field=models.CharField(
                blank=True,
                choices=[
                    (None, "unknown"),
                    ("wetland", "wetland"),
                    ("coastline", "coastline"),
                    ("bay", "bay"),
                    ("river", "river"),
                    ("stream", "stream"),
                    ("tidal_channel", "tidal channel"),
                    ("canal", "canal"),
                    ("drain", "drain"),
                    ("ditch", "ditch"),
                    ("lagoon", "lagoon"),
                    ("oxbow", "oxbow"),
                    ("lake", "lake"),
                    ("basin", "basin"),
                    ("harbour", "harbour"),
                    ("pond", "pond"),
                    ("reservoir", "reservoir"),
                    ("wastewater", "wastewater"),
                    ("spring", "spring"),
                ],
                max_length=16,
                verbose_name="Water type",
            ),
        ),
        migrations.AlterField(
            model_name="water",
            name="geometry",
            field=django.contrib.gis.db.models.fields.GeometryCollectionField(
                srid=4326, verbose_name="Geometry"
            ),
        ),
        migrations.AlterField(
            model_name="water",
            name="name",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="water",
            name="osm_id",
            field=models.BigIntegerField(null=True, verbose_name="OpenStreetMap ID"),
        ),
    ]
