# Generated by Django 4.0.3 on 2022-03-28 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcampuscore', '0034_update_measurement_search'),
    ]

    operations = [
        migrations.AlterField(
            model_name='water',
            name='osm_element_type',
            field=models.CharField(blank=True, choices=[(None, 'unknown'), ('node', 'node'), ('way', 'way'), ('relation', 'relation')], max_length=16, null=True),
        ),
    ]
