# Generated by Django 4.0.3 on 2022-03-28 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gcampuscore', '0031_parametertype_calibration_formula_and_more'),
        ('gcampuscore', '0031_parametertype_short_name_alter_measurement_comment_and_more'),
        ('gcampuscore', '0035_alter_water_osm_element_type'),
    ]

    operations = [
    ]
