# Generated by Django 4.0.2 on 2022-03-16 17:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gcampuscore', '0035_alter_water_flow_type_alter_water_water_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='water',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='water',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
