#  Copyright (C) 2021 desklab gUG
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
#
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.

# Generated by Django 3.1.7 on 2021-06-14 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TeacherToken",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("token", models.CharField(max_length=12, unique=True)),
                ("deactivated", models.BooleanField(default=False)),
                (
                    "school_name",
                    models.CharField(
                        blank=True, max_length=140, verbose_name="School Name"
                    ),
                ),
                (
                    "teacher_name",
                    models.CharField(
                        blank=True, max_length=140, verbose_name="Teacher Name"
                    ),
                ),
            ],
            options={
                "verbose_name": "Teacher Token",
            },
        ),
        migrations.CreateModel(
            name="StudentToken",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("token", models.CharField(max_length=8, unique=True)),
                ("deactivated", models.BooleanField(default=False)),
                (
                    "parent_token",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="gcampusauth.teachertoken",
                    ),
                ),
            ],
            options={
                "verbose_name": "Student Token",
            },
        ),
    ]
