# Generated by Django 3.1.7 on 2021-06-14 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TeacherToken",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("token", models.CharField(max_length=12, unique=True)),
                ("deactivated", models.BooleanField(default=False)),
                (
                    "school_name",
                    models.CharField(
                        blank=True, max_length=140, verbose_name="School Name"
                    ),
                ),
                (
                    "teacher_name",
                    models.CharField(
                        blank=True, max_length=140, verbose_name="Teacher Name"
                    ),
                ),
            ],
            options={
                "verbose_name": "Teacher Token",
            },
        ),
        migrations.CreateModel(
            name="StudentToken",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("token", models.CharField(max_length=8, unique=True)),
                ("deactivated", models.BooleanField(default=False)),
                (
                    "parent_token",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="gcampusauth.teachertoken",
                    ),
                ),
            ],
            options={
                "verbose_name": "Student Token",
            },
        ),
    ]
