# Generated by Django 4.0.3 on 2022-04-14 08:50
import django.db.models.deletion
from celery.utils import noop
from django.db import migrations, models, transaction

from gcampus.auth.models import CourseToken, AccessKey


def update_permissions(apps, schema_editor):
    with transaction.atomic():
        for course_token in CourseToken.objects.all():
            course_token.apply_default_permissions()
            course_token.save()
        for access_key in AccessKey.objects.all():
            access_key.apply_default_permissions()
            access_key.save()


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("gcampusauth", "0002_course"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursetoken",
            name="course",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="course_token",
                to="gcampusauth.course",
            ),
        ),
        migrations.AlterModelOptions(
            name="course",
            options={"verbose_name": "Course", "verbose_name_plural": "Courses"},
        ),
        # Email confirmation
        migrations.AddField(
            model_name="course",
            name="email_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="course",
            name="new_email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="pending email"
            ),
        ),
        # Last login
        migrations.AddField(
            model_name="accesskey",
            name="last_login",
            field=models.DateTimeField(
                blank=True, default=None, null=True, verbose_name="Last login"
            ),
        ),
        migrations.AddField(
            model_name="coursetoken",
            name="last_login",
            field=models.DateTimeField(
                blank=True, default=None, null=True, verbose_name="Last login"
            ),
        ),
        # Permissions
        migrations.AddField(
            model_name="accesskey",
            name="permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this access key.",
                related_name="access_key_set",
                related_query_name="access_key",
                to="auth.permission",
                verbose_name="access key permissions",
            ),
        ),
        migrations.AddField(
            model_name="coursetoken",
            name="permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this course token.",
                related_name="course_token_set",
                related_query_name="course_token",
                to="auth.permission",
                verbose_name="course token permissions",
            ),
        ),
        migrations.RunPython(
            update_permissions,
            reverse_code=noop,  # Do nothing as the permissions are deleted anyway
        ),
    ]
