# Generated by Django 4.0.3 on 2022-04-16 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gcampusauth", "0003_email_permissions_last_login"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="accesskey",
            options={
                "ordering": ("deactivated", "created_at", "token"),
                "verbose_name": "Access key",
            },
        ),
    ]
