# Generated by Django 5.2.3 on 2025-06-28 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "gcampusauth",
            "0005_alter_accesskey_options_alter_coursetoken_options_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="BlockedEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("email", models.EmailField(max_length=254, verbose_name="email")),
                (
                    "internal_comment",
                    models.TextField(
                        blank=True, null=True, verbose_name="internal comment"
                    ),
                ),
            ],
            options={
                "verbose_name": "Blocked email",
                "verbose_name_plural": "Blocked emails",
            },
        ),
    ]
