# Generated by Django 3.2.8 on 2021-12-05 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcampusauth', '0010_auto_20211126_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursetoken',
            name='overview_document',
            field=models.FileField(blank=True, null=True, upload_to='documents/course/overview', verbose_name='Overview Document'),
        ),
    ]
