name: Build and Deploy

on:
  release:
    # The tag will be available at ${{ env.GITHUB_REF }}
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
#
#      - name: Extract metadata (tags, labels) for Docker
#        id: meta
#        uses: docker/metadata-action@v3
#        with:
#          images: ghcr.io/${{ github.repository }}
#          # In the code below, we enable the 'dev' or 'latest' tag depending
#          # on the release type. For more information about the release
#          # webhook and what variables are available, see
#          # https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#release
#          tags: |
#            type=semver,pattern={{version}}
#            type=raw,value=dev,enable=${{ github.event.release.action == 'prereleased' }}
#          flavor: |
#            latest=${{ github.event.release.action == 'released' }}
#
#      - name: Build and push
#        uses: docker/build-push-action@v2
#        with:
#          context: .
#          push: true
#          tags: ${{ steps.meta.outputs.tags }}
#          labels: ${{ steps.meta.outputs.labels }}
