name: Build Static Files

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  static:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5

      - name: Install Node.js packages
        run: npm ci --also=dev

      - name: Build static files
        run: npm run build

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.9
          mamba-version: "*"
          channels: conda-forge,defaults
          channel-priority: true
          activate-environment: gcampus

      - name: Install Python and GDAL
        shell: bash -l {0}
        run: |
          conda activate gcampus
          mamba install -y libgdal -c conda-forge

      - name: Install Requirements
        shell: bash -l {0}
        run: |
          conda activate gcampus
          pip install -r requirements.txt

      - name: Upload static files
        run: |
          conda activate gcampus
          python manage.py collectstatic --no-input
        shell: bash -l {0}
        env:
          USE_S3_STORAGE: True
          S3_ACCESS_KEY: ${{secrets.MINIO_ACCESS_KEY}}
          S3_SECRET_KEY: ${{secrets.MINIO_SECRET_KEY}}
          S3_ENDPOINT_URL: 'https://static.desk-lab.de'
          S3_BUCKET_NAME: 'gcampus'
