name: Build Static Files

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build-static:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5

      - name: Install Node.js packages
        run: npm ci --also=dev
      - name: Build static files
        run: npm run build
      
      - name: Setup Python
        uses: actions/setup-python@v2.2.1
        with:
          python-version: '3.x'
      
      - name: Install Requirements
        run: pip install -r requirements.txt

      - name: Upload static files
        run: python manage.py collectstatic --no-input
        env:
          USE_S3_STORAGE: True
          S3_ACCESS_KEY: ${{secrets.MINIO_ACCESS_KEY}}
          S3_SECRET_KEY: ${{secrets.MINIO_SECRET_KEY}}
          S3_ENDPOINT_URL: 'https://static.desk-lab.de'
          S3_BUCKET_NAME: 'gcampus'
